version: "3.8"
services:
  todo-list:
    image: todo-list
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
